<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
	    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
	    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
	    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
	    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
	    <None Include="Documents\Template.rtf">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    </None>
        <None Update="Documents\Detail1.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Documents\Detail2.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.Win.RichEdit" Version="23.1.*" />
    </ItemGroup>
</Project>