<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>WinExe</OutputType>
        <AppDesignerFolder>Properties</AppDesignerFolder>
        <RootNamespace></RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <UseWindowsForms>true</UseWindowsForms>
        <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    </PropertyGroup>
    <ItemGroup>
        <Compile Update="Form1.Designer.vb">
            <DependentUpon>Form1.vb</DependentUpon>
        </Compile>
        <Compile Update="Properties\Resources.Designer.vb">
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
            <DesignTime>True</DesignTime>
        </Compile>
        <None Update="Documents\Detail1.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Documents\Detail2.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="Documents\Template.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <Compile Update="Properties\Settings.Designer.vb">
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.Win.RichEdit" Version="23.1.*" />
    </ItemGroup>
</Project>